name: ReleaseBuild

on:
push:
branches:
- master

env:
# リポジトリのルートディレクトリを基点としたソリューションファイルのパス
SOLUTION_FILE_PATH: project/CG2.sln
# VisualStudio の構成(DEebug / Release )
CONFIGURATION: Release

jobs:
build:
runs-on: windows-2022

steps:
- name: checkout
uses: actions/checkout@v4
- name: Add MSBuild to PATH
uses: microsoft/setup-msbuild@v2
with:
msbuild-architecture: x64
- name: Build
run : |
msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
